export const Dummypackages={
    package:[
       
        {
            price:15,
            type:"Strarter",
            monthly:true,
            yearly:false,
            paperlinkfiles:1,
            teammembers:1,
            ccflow:1,
            publicprofile:2,
            pdfcopy:2,
            promoted:false
        },
        {
            price:20,
            type:"Promoted",
            monthly:true,
            yearly:false,
            paperlinkfiles:1,
            teammembers:1,
            ccflow:1,
            publicprofile:2,
            pdfcopy:2,
            promoted:true
        },
        {
            price:13,
            type:"Standard",
            monthly:true,
            yearly:false,
            paperlinkfiles:1,
            teammembers:1,
            ccflow:2,
            publicprofile:3,
            pdfcopy:3,
            promoted:false
        },
        {
            price:20,
            type:"Promoted",
            monthly:true,
            yearly:false,
            paperlinkfiles:1,
            teammembers:1,
            ccflow:1,
            publicprofile:2,
            pdfcopy:2,
            promoted:true
        },
        {
            price:20,
            type:"Promoted",
            monthly:true,
            yearly:false,
            paperlinkfiles:1,
            teammembers:1,
            ccflow:1,
            publicprofile:2,
            pdfcopy:2,
            promoted:true
        },

    ]
}